# Generated by Django 3.1.7 on 2021-03-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_newsletterusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_posts',
            name='likes',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
