# Generated by Django 3.1.7 on 2021-03-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_auto_20210330_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image_posts',
            name='created_date',
        ),
    ]
